---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Build ibm-sandbox-cleanup
  name: ibm-sandbox-cleanup-build

parameters:
- name: NAME
  required: true
  value: ibm-sandbox-cleanup
- name: PYTHON_S2I_IMAGE
  required: true
  value: registry.access.redhat.com/ubi9/python-311:latest
- name: GIT_REPO
  required: true
  value: https://github.com/redhat-gpte/ibm-sandbox-cleanup.git
- name: GIT_REF
  required: true
  value: fix-cleanup
- name: CONTEXT_DIR
  value: cleanup

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        forcePull: true
        from:
          kind: DockerImage
          name: ${PYTHON_S2I_IMAGE}
    triggers: []
...
