{{- if .Values.deploy }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ibm-sandbox-cleanup.name" . }}
  labels:
    {{- include "ibm-sandbox-cleanup.labels" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: "Forbid"
  suspend: {{ .Values.suspendCronJob }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: ibm-sandbox-cleanup-dynamodb
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: {{ include "ibm-sandbox-cleanup.name" . }}-dynamodb
              - name: AWS_REGION
                valueFrom:
                  secretKeyRef:
                    key: aws_region
                    name: {{ include "ibm-sandbox-cleanup.name" . }}-dynamodb
              - name: SAA_URL
                value: "{{ .Values.sandboxAssignmentAPI.url }}"
              - name: IBM_USAGE_DB
                value: sandbox_billing
              - name: SAA_API_KEY
                valueFrom:
                  secretKeyRef:
                    key: api_key
                    name: {{ include "ibm-sandbox-cleanup.name" . }}-saa-credential
              {{- if ".Values.prometheus-pushgateway.enabled" }}
              - name: PUSH_GATEWAY_URL
                value: "{{ .Release.Name }}-prometheus-pushgateway.{{ .Release.Namespace }}.svc.cluster.local:9091"
              {{- end }}
          restartPolicy: Never
{{- end }}
