{{- if .Values.sandboxAssignmentAPI.api_key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibm-sandbox-cleanup.fullname" . }}-saa-credential
  labels:
    {{- include "ibm-sandbox-cleanup.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.sandboxAssignmentAPI.api_key | b64enc }}
{{- end -}}
